<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LNUS5CG91852P3" failures="2" tests="8" name="production_itineraries.InsuranceItineraryTest" time="108.502" errors="0" timestamp="2025-09-13T18:21:27 CDT" skipped="6">
  <testcase classname="production_itineraries.InsuranceItineraryTest" name="testcases_InsuranceItineraryTest" time="6.545">
    <skipped/>
  </testcase> <!-- testcases_InsuranceItineraryTest -->
  <testcase classname="production_itineraries.InsuranceItineraryTest" name="testcases_InsuranceItineraryTest" time="6.627">
    <skipped/>
  </testcase> <!-- testcases_InsuranceItineraryTest -->
  <testcase classname="production_itineraries.InsuranceItineraryTest" name="testcases_InsuranceItineraryTest" time="20.143">
    <skipped/>
  </testcase> <!-- testcases_InsuranceItineraryTest -->
  <testcase classname="production_itineraries.InsuranceItineraryTest" name="testcases_InsuranceItineraryTest" time="20.741">
    <failure message="expected [The WebElement &quot;&#039;Expand Itineraries Section&#039; Button&quot; was clicked] but found [The WebElement &quot;&#039;Expand Itineraries Section&#039; Button&quot; is not clickable]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [The WebElement "'Expand Itineraries Section' Button" was clicked] but found [The WebElement "'Expand Itineraries Section' Button" is not clickable]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at utilityClasses.ReportLoggerMethods.click(ReportLoggerMethods.java:124)
at pagemethods.ClientfilePage.openInsuranceItineraryPage(ClientfilePage.java:100)
at production_itineraries.InsuranceItineraryTest.testcases_InsuranceItineraryTest(InsuranceItineraryTest.java:67)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- testcases_InsuranceItineraryTest -->
  <testcase classname="production_itineraries.InsuranceItineraryTest" name="testcases_InsuranceItineraryTest" time="21.245">
    <skipped/>
  </testcase> <!-- testcases_InsuranceItineraryTest -->
  <testcase classname="production_itineraries.InsuranceItineraryTest" name="testcases_InsuranceItineraryTest" time="6.845">
    <skipped/>
  </testcase> <!-- testcases_InsuranceItineraryTest -->
  <testcase classname="production_itineraries.InsuranceItineraryTest" name="testcases_InsuranceItineraryTest" time="6.567">
    <failure message="expected [The WebElement &quot;&#039;Expand Itineraries Section&#039; Button&quot; was clicked] but found [The WebElement &quot;&#039;Expand Itineraries Section&#039; Button&quot; is not clickable]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [The WebElement "'Expand Itineraries Section' Button" was clicked] but found [The WebElement "'Expand Itineraries Section' Button" is not clickable]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at utilityClasses.ReportLoggerMethods.click(ReportLoggerMethods.java:124)
at pagemethods.ClientfilePage.openInsuranceItineraryPage(ClientfilePage.java:100)
at production_itineraries.InsuranceItineraryTest.testcases_InsuranceItineraryTest(InsuranceItineraryTest.java:67)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- testcases_InsuranceItineraryTest -->
  <testcase classname="production_itineraries.InsuranceItineraryTest" name="testcases_InsuranceItineraryTest" time="19.789">
    <skipped/>
  </testcase> <!-- testcases_InsuranceItineraryTest -->
</testsuite> <!-- production_itineraries.InsuranceItineraryTest -->
