<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LNUS5CG91852P3" failures="1" tests="6" name="testcases.ClientfileSearchTest" time="105.666" errors="0" timestamp="2025-07-22T17:09:36 CDT" skipped="0">
  <testcase classname="testcases.ClientfileSearchTest" name="testcases_ClientfileSearchTest" time="14.181"/>
  <testcase classname="testcases.ClientfileSearchTest" name="testcases_ClientfileSearchTest" time="14.905"/>
  <testcase classname="testcases.ClientfileSearchTest" name="testcases_ClientfileSearchTest" time="15.308"/>
  <testcase classname="testcases.ClientfileSearchTest" name="testcases_ClientfileSearchTest" time="27.130">
    <failure message="The following asserts failed:
	expected [] but found [W44]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [] but found [W44]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testcases.ClientfileSearchTest.testcases_ClientfileSearchTest(ClientfileSearchTest.java:127)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- testcases_ClientfileSearchTest -->
  <testcase classname="testcases.ClientfileSearchTest" name="testcases_ClientfileSearchTest" time="21.142"/>
  <testcase classname="testcases.ClientfileSearchTest" name="testcases_ClientfileSearchTest" time="13.000"/>
</testsuite> <!-- testcases.ClientfileSearchTest -->
